- .env
- terraso_backend/apps/auth/urls.py
- terraso_backend/apps/auth/views.py
- terraso_backend/config/settings.py
- terraso_backend/tests/auth/test_views.py
This change adds the endpoint responsible for processing the Apple
and Google callback after user authorize Terraso application access 
their data. By the end of the success process, the API procedure will
redirect user back to the web client application with auth details 
attached in a cookie.
It's important to mention that the cookie value isn't still a JWT because
this part depends on integrating this PR with the following one:
- #48 
I intend to do that in a separated PR.
> feat: add authentication callback for Google and Apple

- terraso_backend/apps/auth/views.py
- terraso_backend/tests/auth/test_views.py
This change updates the callback process of sign up to create two
cookies for access token and refresh token respectively. Each cookie 
(`atoken`, `rtoken`) will keep its own token instead of serializing a
JSON object for that. This is necessary both to make client work 
more straightforward and to avoid serialization errors.
> fix: set one cookie for each JWT token after sign up

- terraso_backend/apps/auth/views.py
- terraso_backend/apps/graphql/views.py
- terraso_backend/tests/auth/test_views.py
This change updates the HTTP response status code for unauthenticated
requests. Before it was returning 403 (Forbidden) while 401
(Unauthorized) is more appropriate.
> fix: returns 401 status code for unauthenticated requests

- terraso_backend/apps/auth/services.py
- terraso_backend/apps/auth/views.py
- terraso_backend/tests/auth/test_views.py
This change updates the Apple process for logins after the sign-up.
Since Apple shares user name only during the first authentication flow
(sign up), the process cannot consider the user names will always be
available.
The previous implementation was allowing to update user names with empty
string, specially during Apple sign in, but it was also possible for
Google. This change fixes that and assure the user names are updated only
if there's some content.
> fix: Apple login after sign-up

- terraso_backend/apps/auth/views.py
This change makes a generalization from Google and Apple authorize and
callback views into more generic ones. This way we implement only once the
common procedure on these processes.
> refactor: authorization views

- terraso_backend/apps/auth/mixins.py
- terraso_backend/apps/auth/views.py
- terraso_backend/apps/graphql/views.py
- terraso_backend/tests/graphql/conftest.py
- terraso_backend/tests/graphql/test_auth_request.py
This change creates a mixin to centralize the check if user is logged in
or not. It also properly builds the response object with the expected
status code. It's worth to see that for requests with authentication
failure, the response will always be a JSON response with a proper HTTP
status code (401).
The added mixin is intended to be used instead of multiplying across the
code base the verification `if not user.is_authenticated`. So, on every
view that is making this check, the `AuthenticationRequiredMixin` should
be used instead.
The Django's `LoginRequiredMixin` wasn't used because:
1 - It returns 403 responses for non authenticated requests;
2 - There are only redirect or HTML responses in case of authentication
failure and we need a JSON response since it's more convenient for our …
> refactor: creates AuthenticationRequiredMixin to auth check

- terraso_backend/apps/graphql/schema/commons.py
- terraso_backend/apps/graphql/schema/group_associations.py
- terraso_backend/apps/graphql/schema/groups.py
- terraso_backend/apps/graphql/schema/landscape_groups.py
- terraso_backend/apps/graphql/schema/landscapes.py
- terraso_backend/apps/graphql/schema/memberships.py
- terraso_backend/apps/graphql/schema/users.py
- terraso_backend/tests/graphql/mutations/test_group_associations_mutations.py
- terraso_backend/tests/graphql/mutations/test_group_mutations.py
- terraso_backend/tests/graphql/mutations/test_landscape_groups_mutations.py
- terraso_backend/tests/graphql/mutations/test_landscape_mutations.py
- terraso_backend/tests/graphql/mutations/test_membership_mutations.py
- terraso_backend/tests/graphql/mutations/test_user_mutations.py
This change updates the GraphQL API schemas to use the same database id
(UUID) on model schemas.
> feat: use model pk UUID as API id

- sampledata.json
This change removes an unexpected group from the Sample Data file.
Fix: #83
> chore: removes no-formal-partnerthip Group from sample data

- Makefile
- scripts/docker.sh
Check if Docker is running before calling `docker-compose` up. Avoids long, messy errors like so:
```
$ make run
./scripts/rebuild.sh
Checking if we need a docker images rebuild before running this command
docker build --tag=techmatters/terraso_backend --file=Dockerfile .
Cannot connect to the Docker daemon at unix:///var/run/docker.sock. Is the docker daemon running?
ERRO[0000] Can't add file /Users/paul/.dev/backend/.git/hooks/pre-push.sample to tar: io: read/write on closed pipe 
make[1]: *** [build_base_image] Error 1
make: *** [check_rebuild] Error 2
```
> build: check if docker is running before calling docker-compose up

- terraso_backend/apps/auth/services.py
- terraso_backend/tests/auth/test_services.py
This change updates the Account Service to make sure the user name is
only set when user is created. If the user signing in was already
created on database, then their names will be left as is. This is
important because users might have had updated their names on Terraso
platform after the sign-up process.
> fix: user names being updated on every sign in

- terraso_backend/apps/graphql/schema/__init__.py
- terraso_backend/apps/graphql/schema/commons.py
- terraso_backend/tests/graphql/test_core_request.py
This change fixes a bug inserted by the change that updated the GraphQL
API global ID for nodes to use model PK (Primary key). After that
change, that overridden default relay global ID, it wasn't possible any
more get one specific node by its ID.
What this change does is to create a custom relay Node that knows how to
search for a specific model from global ID, using its PK.
> fix: get one node by id on GraphQL API

- terraso_backend/apps/core/models/groups.py
- terraso_backend/apps/graphql/schema/memberships.py
- terraso_backend/tests/core/models/test_groups.py
- terraso_backend/tests/graphql/mutations/test_membership_mutations.py
This change updates the `Group.save()` method to automatically create a
`Membership` as role manager for the group creator.
It also updates the `addMembership` mutation on GraphQL to be
idempotent. It means that, if the same pair of `user` and `group` be
submitted to membership creation more than once, only one membership
will be created.
This change is necessary in a context where the web client is having to
create the Group manager directly because the back-end hadn't this
automatic creation implemented.
Now that the back-end implements the automatic manager creation, we have
to create the conditions to release it without breaking the current
implementation of web client.
So, after this change, we can release the automatic group manager
creation on the API side without the need to sync …
> feat: adds Group Manager creation when Group is created

- requirements-dev.txt
- requirements.txt
- requirements/base.in
- terraso_backend/apps/core/models/commons.py
- terraso_backend/apps/core/models/groups.py
- terraso_backend/apps/core/models/users.py
- terraso_backend/apps/core/permission_rules.py
- terraso_backend/apps/graphql/schema/groups.py
- terraso_backend/config/settings.py
- terraso_backend/tests/core/models/test_groups.py
- terraso_backend/tests/graphql/mutations/test_group_mutations.py
This change adds permissions check to allow only Users with Group
Manager role to update Group data.
The permissions check works based on `django-rules`[1] lib.
One of the core concepts of `django-rules` are the `predicates`.
Predicates are simple _callables_ that returns a boolean value as a
permission result. The way it was set on the project, all our predicates
should be defined only on `apps.core.permission_rules`.
The base models were updated to integrate with `django-rules` and to
make possible to associate the predicates directly on model definition
(Meta class). This way is somehow explicit which permissions are related
to each model and to which model operation (create, update, delete).
On any place where we need to check for permission before an operation,
we can do it calling …
> feat: allows only Group Manager update Group data

- terraso_backend/apps/core/models/groups.py
- terraso_backend/apps/core/models/landscapes.py
- terraso_backend/apps/core/models/users.py
- terraso_backend/apps/core/permission_rules.py
- terraso_backend/apps/graphql/schema/groups.py
- terraso_backend/apps/graphql/schema/landscapes.py
- terraso_backend/tests/core/models/test_users.py
- terraso_backend/tests/graphql/conftest.py
- terraso_backend/tests/graphql/mutations/test_group_mutations.py
- terraso_backend/tests/graphql/mutations/test_landscape_mutations.py
This change adds:
- Permission checks to delete Landscape;
- Permission checks to update Landscape;
- Permission checks to delete Group;
It implements:
- #69
> feat: permissions to delete / change Group and Landscape

- terraso_backend/config/settings.py
The auth.W004 warning says that user username field is not unique. This
change silence this warning because we have a unique constraint in
place, but considering only non deleted objects.
> chore: silence system auth.W004 warning

- terraso_backend/apps/graphql/schema/groups.py
- terraso_backend/tests/graphql/test_groups_filters.py
There was a specific case where using Django built-in lookups for
relationships don't work properly with the soft delete solution we
implemented with `django-safedelete`. According to the library
maintainers, it's a known limitation[1].
To work around this limitation, a customized filter set were created for
Group schema on GraphQL. This custom filter set implements the
adjustments expected to ignore soft deleted objects when filtering by
relationships (joins).
[1] - https://github.com/makinacorpus/django-safedelete/issues/158
> fix: GraphQL Group filters using deleted associated objects

- terraso_backend/apps/graphql/schema/__init__.py
- terraso_backend/apps/graphql/schema/landscape_groups.py
- terraso_backend/tests/graphql/mutations/test_landscape_groups_mutations.py
Landscape Group (the relationship model between Landscape and Group)
isn't expected to be updated. The only attribute this entity has is the
`is_default_landscape_group` that is a more internal attribute and won't
be updated.
> feat: removes LandscapeGroupUpdateMutation

- terraso_backend/apps/core/models/landscapes.py
- terraso_backend/apps/core/permission_rules.py
- terraso_backend/apps/graphql/schema/landscape_groups.py
- terraso_backend/tests/graphql/mutations/test_landscape_groups_mutations.py
This change adds permission check to allow only Landscape managers to
add Landscape Group. It means only a Landscape Manager can create a new
association to a Group.
It also adds permission check to allow only the Landscape or Group
manager to delete a Landscape Group relationship.
- #75
> feat: adds permission checks to mutate Landscape Group

- terraso_backend/apps/core/models/groups.py
- terraso_backend/apps/core/permission_rules.py
- terraso_backend/apps/graphql/schema/group_associations.py
- terraso_backend/tests/graphql/mutations/test_group_associations_mutations.py
This change adds the proper permission checks to the Group Association
add and delete mutations.
`GroupAssociation` is the relationship entity between two `Groups`.
- #75
> feat: add permissions to GroupAssociation mutations

- terraso_backend/apps/core/models/groups.py
- terraso_backend/apps/core/permission_rules.py
- terraso_backend/apps/graphql/schema/memberships.py
- terraso_backend/tests/graphql/mutations/test_membership_mutations.py
This change adds the proper permission check to change a Membership.
Since the only attribute to be updated in a Membership object is the
user role, only the Membership group manager is allowed to make this
mutation.
> feat: add permission to change Membership

- terraso_backend/apps/graphql/schema/memberships.py
- terraso_backend/tests/graphql/mutations/test_membership_mutations.py
This change updates the permissions checks on Membership update mutation
to don't allow the last Group Manager to become a Member.
> fix: doesn't allow last manager to become a member

- terraso_backend/apps/auth/providers.py
- terraso_backend/apps/auth/views.py
This change adds the `state` parameter to the `{provider}/authorize`
API. This endpoint returns the proper provider URL to redirect the user to
authentication. Now, this API accepts a `state` parameter that will be
used to redirect back user to the client. Example:
If the authorize URL for Google be request like:
```
/auth/google/authorize?state=groups/new
```
After a successful authentication, the user will be redirected to
`{web_client_endpoint}/groups/new`.
> feat: add state parameter to authorize URL API

- terraso_backend/apps/graphql/exceptions.py
- terraso_backend/apps/graphql/formatters.py
- terraso_backend/apps/graphql/schema/commons.py
- terraso_backend/apps/graphql/schema/constants.py
- terraso_backend/apps/graphql/schema/group_associations.py
- terraso_backend/apps/graphql/schema/groups.py
- terraso_backend/apps/graphql/schema/landscape_groups.py
- terraso_backend/apps/graphql/schema/landscapes.py
- terraso_backend/apps/graphql/schema/memberships.py
- terraso_backend/apps/graphql/schema/users.py
- terraso_backend/tests/graphql/mutations/test_group_associations_mutations.py
- terraso_backend/tests/graphql/mutations/test_group_mutations.py
- terraso_backend/tests/graphql/mutations/test_landscape_groups_mutations.py
- terraso_backend/tests/graphql/mutations/test_landscape_mutations.py
- terraso_backend/tests/graphql/mutations/test_membership_mutations.py
- terraso_backend/tests/graphql/mutations/test_user_mutations.py
- terraso_backend/tests/graphql/test_formatters.py
This change updates how the validation messages are built. It now makes
the message be a serialized JSON in order to add more contextual data to
the message. This is an attempt to make possible the i18n of validation
messages by the clients.
This is an example of validation error message using the new schema:
```
'message': '[{
"code": "updateNotAllowed",
"context": {"model": null, "field": "membership"}
}]'
```
If the validation happens in a specific field, the context `field`
attribute will have the related field name. Otherwise, it will be null. 
```
'message': '[{
"code": "notFound",
"context": {"model": "Membership", "field": "group", "extra": ""}
}]'
```
In some specific cases, an error message might have a complement to the
error code. Like in a situation where a `Membership` …
> feat: add error codes to validation error responses

- terraso_backend/apps/graphql/schema/groups.py
This change removes `member__email` Group filter field. It was replaced
by `memberships__email`.
Fix: #105
> chore: remove member__email Group filter field

- terraso_backend/apps/graphql/schema/memberships.py
- terraso_backend/tests/graphql/mutations/test_membership_mutations.py
During mutations refactoring, a call to `super()` was left on membership
update mutation process, but the mutations' inheritance structure was
changed. This call was being made based on the value of
`CHECK_PERMISSIONS` feature flag and the test was not covering the 
buggy path. So, the test was also updated to cover it.
Fix: #123
> fix: Membership update mutation

- terraso_backend/config/settings.py
This change adds the settings to the application serve the static files
from S3 (through Cloudflare).
- #25
> chore: adds settings to serve static files from CDN

- terraso_backend/config/settings.py
This change sets the JSON log formatter to the console logger. This way
we can have the log parsed on log management platforms.
- #78
> chore: sets JSON log formatter to console log

- terraso_backend/apps/graphql/schema/group_associations.py
- terraso_backend/apps/graphql/schema/groups.py
- terraso_backend/apps/graphql/schema/landscape_groups.py
- terraso_backend/apps/graphql/schema/landscapes.py
- terraso_backend/apps/graphql/schema/memberships.py
- terraso_backend/config/settings.py
- terraso_backend/tests/graphql/mutations/test_group_associations_mutations.py
- terraso_backend/tests/graphql/mutations/test_group_mutations.py
- terraso_backend/tests/graphql/mutations/test_landscape_groups_mutations.py
- terraso_backend/tests/graphql/mutations/test_landscape_mutations.py
- terraso_backend/tests/graphql/mutations/test_membership_mutations.py
The `CHECK_PERMISSIONS` feature flag was created to be used only until
web client implement behavior changes based on user's role. Now, we can
always run permissions check. So, the feature flag is being removed.
Fix: #125
> chore: removes check permissions feature flag

- terraso_backend/apps/core/admin.py
This change registers the models from the `core` to Django admin.
Fix: #25
> feat: add core models to admin panel

- terraso_backend/apps/graphql/schema/landscapes.py
This change adds the `area_polygon` Landscape's attribute to the
update mutation schema.
> feat: adds Landscape area polygon to update mutation

- terraso_backend/apps/graphql/exceptions.py
- terraso_backend/tests/graphql/mutations/test_group_associations_mutations.py
- terraso_backend/tests/graphql/mutations/test_group_mutations.py
- terraso_backend/tests/graphql/mutations/test_landscape_groups_mutations.py
- terraso_backend/tests/graphql/mutations/test_landscape_mutations.py
- terraso_backend/tests/graphql/mutations/test_membership_mutations.py
- terraso_backend/tests/graphql/mutations/test_user_mutations.py
- Keep error codes snake cased to handle them better on the client side
> fix: Keep error codes snake cased

- terraso_backend/apps/graphql/schema/commons.py
- terraso_backend/tests/graphql/mutations/test_group_mutations.py
- terraso_backend/tests/graphql/mutations/test_landscape_mutations.py
This change fixes the response message for duplicated slug scenarios
when using the generic write mutation. As a good collateral effect, this
change already handle any integrity error that might happen.
The slug unique constraint only runs over non-deleted registers. This
constraint is created directly on DB. So, when performing a save
operation, this unique constraint will only be assessed on DB level, not
on application level. The DB error message is the message being returned
by the API at the moment.
This change handles the `IntegrityError` when calling `save()` and build
an appropriate `ValidationError` to be returned by the API.
Example of the result message:
```
{
"message": '[{
"code": "unique",
"context": {"model": "Group", "field": "All", "extra": ""}
}]', 
...
}
```
fix: #147
> fix: duplicated slug message returned by the API

- terraso_backend/apps/graphql/schema/__init__.py
- terraso_backend/apps/graphql/schema/shared_data.py
- terraso_backend/apps/shared_data/admin.py
- terraso_backend/apps/shared_data/models.py
- terraso_backend/tests/graphql/conftest.py
- terraso_backend/tests/graphql/mutations/test_shared_data_mutations.py
- terraso_backend/tests/graphql/test_shared_data.py
This change creates the GraphQL API for the Shared Data Files app with the
operations to read, update and delete `DataEntry`.
> feat: create the GraphQL API of shared data app

- terraso_backend/apps/core/urls.py
- terraso_backend/apps/core/views.py
- terraso_backend/config/urls.py
- terraso_backend/tests/core/test_views.py
This change adds a simple health check endpoint. During the check, the
main database tables are read. If any error be raised, an HTTP 400
response is returned. An HTTP 200 (success) is returned otherwise.
This endpoint will be used by Render to check the status of new deployments[1].
[1] - https://render.com/docs/deploys#health-checks
> feat: add simple health check endpoint

- terraso_backend/apps/storage/services.py
This change creates an abstract upload service based on the current
profile image service. This way, new services that make upload can be
created based on the abstract one having simpler specialized
implementation. No internal API changes were made in this change.
This is part of work for:
- #154 
- #152
> refactor: creates an abstract upload service

- terraso_backend/apps/graphql/schema/shared_data.py
- terraso_backend/tests/graphql/conftest.py
- terraso_backend/tests/graphql/test_shared_data.py
This change makes the GraphQL query for `DataEntry` return only those
registers associated to the Groups from the logged user.
> feat: restrict DataEntry list to group members only

- terraso_backend/apps/shared_data/models.py
- terraso_backend/apps/storage/services.py
This change updates the generic upload service to S3 to generate URLs
without spaces, using %20 instead. This way the service will generate
valid URLs for URLField from Django.
It also updates the property that gives the S3 object name from a given
`DataEntry` to put back the spaces chars, since this is necessary to the
sign URL process generates valid signed URLs.
> fix: allow file names with spaces on shared files

- terraso_backend/apps/graphql/schema/shared_data.py
To answer only `DataEntry` from groups that the current user is
member of, a specific filter is being done on GraphQL `DataEntryNode`.
Until this change, the query was relying on built-in Django look-ups for
the joins. However, it was including soft-deleted registers (Membership
records) because of not so good integration between Django's look-ups
and the `django-safedelete` lib. This was causing the `DataEntry`
duplication in some groups.
To fix that issue, the query was updated to be more explicit and done in
two steps:
1. Get all ID from `Groups` that the current user is a member of. Since this
is a simple query, the soft-deleted is well respected.
2. With the list of group IDs, filter the `DataEntry` query. This will
also respect the soft-delete underlying conditions
> fix: duplicated Data Entries on API response

- terraso_backend/apps/shared_data/permission_rules.py
- terraso_backend/tests/shared_data/test_models.py
This change updates the permission rule to delete `DataEntry` to allow
Group managers to delete files in their groups.
Fix:
- #181
> feat: allow Group manager delete shared files

- terraso_backend/config/settings.py
- This change updates how the OIDC private key is loaded from environment
variables, so we can work with multi-line values.
- After latest release of Django OAuth Toolkit, the option `PKCE_REQUIRED`
became `True` as default. This change makes it `False` at least until the
clients start supporting it.
> fix: minor fixes to OAuth provider configs

- terraso_backend/apps/core/models/commons.py
- terraso_backend/apps/core/models/groups.py
- terraso_backend/apps/core/models/landscapes.py
- terraso_backend/apps/core/models/users.py
- terraso_backend/tests/core/models/test_groups.py
- terraso_backend/tests/core/models/test_landscapes.py
- terraso_backend/tests/core/models/test_users.py
Ensures whitespace is trimmed from fields at the model level.
Fixes #159.
> fix: trim whitespace from name and description fields

- terraso_backend/apps/core/models/commons.py
- terraso_backend/apps/core/models/groups.py
- terraso_backend/apps/core/models/landscapes.py
- terraso_backend/config/settings.py
- terraso_backend/tests/core/models/test_groups.py
- terraso_backend/tests/core/models/test_landscapes.py
Disallow "new" as a name for groups and landscapes through a validator.
Fixes #164.
> fix: Disallow "new" as a name for groups and landscapes

- terraso_backend/apps/shared_data/management/commands/clean_up_deleted_files.py
This change updates the cleanup deleted files command to make it fetch
only registers that have `file_removed_at` attribute not set.
> fix: clean up deleted files command

- Dockerfile
Add dnsutils to Dockerfile. Render support believes this will resolve the lookup error:
```
Aug 2 12:02:08 AM  django.db.utils.OperationalError: could not translate host name "dpg-c6t4e7fh8vl8fj5kkua0" to address: Temporary failure in name resolution
```
> chore: add dnsutils to Dockerfile

- terraso_backend/apps/core/geo.py
There is 10,000 meters squared in a hectare, not 1,000
Made a small mistake in the square meters to hectares conversion that I discovered testing on staging.
> fix: fix hectare conversion

- terraso_backend/config/settings.py
It seems like this `context_class` option was included in our structlog setup. However, the feature of context-local logging variables does not seem to have been actually used. I tried removing it and it does not appear to affect the logging output of a few simple requests. As the `threadlocal` module is now deprecated, it makes most sense to remove this config option completely.
My guess is that this was included as part of the default config in the [setup docs for django-structlog](https://django-structlog.readthedocs.io/en/latest/getting_started.html#installation) and never actually used. I didn't verify this though. 
Fixes #195
> fix: Remove unused context class from structlog config

- terraso_backend/apps/core/models/users.py
- terraso_backend/apps/shared_data/models/data_entries.py
- terraso_backend/tests/shared_data/test_models.py
Allows a user to be deleted, even if they have associated data files.
Follows the following logic:
- On a soft delete: linked `data entry` not affected
- On a hard delete: `created_by` field in linked data entry set to null.
Here is the [reference on soft delete policies](https://django-safedelete.readthedocs.io/en/latest/models.html#policies) that will be helpful in code review.
Fixes #190
- Try deleting a user with associated data files
> fix: delete users with shared files

- .github/dependabot.yml
allows dependabot to open more PRs at once, hopefully decreasing chance it will create a dependency conflict without creating a huge flood of PRs. can adjust further as needed
> chore: increase dependabot open PR limit

- terraso_backend/config/settings.py
The default settings of [django-oauth-toolkit](https://github.com/jazzband/django-oauth-toolkit) force the user to reauthorize our OAuth authorization every time the user signs in from an OAuth client. This PR updates the settings so it only prompts for an authorization the first time the user authenticates.
> fix: Change approval setting to only prompt on signup

- terraso_backend/apps/auth/providers.py
use `login.microsoftonline.com` instead of `login.microsoft.com` for the OAuth URL.
> fix: use login.microsoftonline.com instead of login.microsoft.com

- terraso_backend/apps/auth/providers.py
- terraso_backend/config/settings.py
Previously, we had `GOOGLE_AUTH_REDIRECT_URI`, `APPLE_AUTH_REDIRECT_URI` and `MICROSOFT_AUTH_REDIRECT_URI`. 
Now we have `API_ENDPOINT`.
This repeated the same hostname three times, cluttering up the environment variables.
The path part of the URI didn't change from environment to environment; this can stay in the code.
> refactor: use API_ENDPOINT setting instead of individual settings for Google/Apple/MS

- terraso_backend/apps/auth/services.py
If a user signs up with OAuth and the OAuth provider does not provide an email, the backend throws an inscrutable error about database constraints. This helps a bit and displays a clearer error message.
Fixes #304
> fix: Improve error message on missing SSO email

- docker-compose.ci.yml
- docker-compose.dev.yml
Re-add depends_on in extended docker-compose files.
> fix: move depends_on into env specific docker-compose

- terraso_backend/apps/graphql/schema/groups.py
- terraso_backend/apps/graphql/schema/memberships.py
Handle unauthenticated (anonymous) requests for public group information
- provide a 0 for counts for closed groups
- return empty list for members
Web client https://github.com/techmatters/terraso-web-client/issues/324
> fix: handle unauthenticated requests for public group information

- terraso_backend/config/settings.py
Mark sitemap path as public in `PUBLIC_BASE_PATHS`.
> fix: mark sitemap path as public

- Makefile
- scripts/docker.sh
Docker compose v1 is at EOL next month (see https://docs.docker.com/compose/compose-v2/). This updates our scripts to say `docker compose` instead of `docker-compose` so that we are not using an unsupported version in CI (see https://github.com/actions/runner-images/issues/4657#issuecomment-1125700203). This may break people's local workflows, but we should all be making sure to use v2 locally as well.
> chore: use docker compose v2 in CI

- requirements-dev.txt
- terraso_backend/apps/core/models/groups.py
- terraso_backend/apps/graphql/schema/commons.py
- terraso_backend/apps/graphql/schema/schema.graphql
- terraso_backend/apps/graphql/templates/docs.html
Changes the type of our schema's Connection and Edge types from this:
```graphql
type LandscapeGroupNodeConnection {
"""Pagination data for this connection."""
pageInfo: PageInfo!
"""Contains the nodes in this connection."""
edges: [LandscapeGroupNodeEdge]!
totalCount: Int
}
"""A Relay edge containing a `LandscapeGroupNode` and its cursor."""
type LandscapeGroupNodeEdge {
"""The item at the end of the edge"""
node: LandscapeGroupNode
"""A cursor for use in pagination"""
cursor: String!
}
```
to this:
```graphql
type LandscapeGroupNodeConnection {
"""Pagination data for this connection."""
pageInfo: PageInfo!
"""Contains the nodes in this connection."""
edges: [LandscapeGroupNodeEdge!]!
totalCount: Int
}
"""A Relay edge containing a `LandscapeGroupNode` and its cursor."""
type …
```
> types: refine graphql schema connection types

- terraso_backend/apps/auth/constants.py
- terraso_backend/apps/auth/middleware.py
- terraso_backend/apps/auth/views.py
- terraso_backend/config/settings.py
- terraso_backend/tests/auth/test_oauth.py
As described in #478, users currently are not redirected to continue the SSO signin process if they are not signed into their Terraso account. This PR aims to fix this by storing the URI used to start the signin in a cookie. When the user has completed logging into Terraso, we then redirect them to this original URI, starting the process.
How it works:
- User tried to query `/oauth/authorize`; because they are not logged in, the backend redirects them to our "login page", which is just `/`
- I added middleware that just checks if a not logged-in user is trying to query the URI that starts the Terraso SSO provider process (`/oauth/authorize`); if so, the URI is stored in a signed cookie. An expiry date of five minutes is set so that the cookie doesn't hand around forever.
-  User completes …
> fix: Continue SSO signin provision for users not logged into Terraso

- terraso_backend/apps/graphql/schema/data_entries.py
Removes an extra check for group existence that was causing a bug in prod backend.
Fixes https://github.com/techmatters/terraso-product/issues/143
Should now be able to add shared links to groups and landscapes again.
> fix: don't do extraneous group existence check

- Dockerfile
This splits run commands and file copies for faster build times using docker build layer cache
> chore: improve build caching order in Dockerfile

- .env.sample
Adds the `STORY_MAP_MEDIA_S3_BUCKET` key to `.env.sample`, necessary for testing story maps in local dev.
> fix: add missing story map key to .env.sample

- requirements-dev.txt
- requirements.txt
Update boto/botocore versions. Dependabot was unable to upgrade both.
> chore: update boto/botocore versions

- terraso_backend/apps/graphql/schema/sites.py
- terraso_backend/apps/project_management/models/sites.py
- terraso_backend/tests/graphql/teste_sites_query.py
Limits:
- sites owned the user making the query
- sites owned by projects where the user making the query is a member or Project manager
Closes: #556
> feat: add permissions for site query

- terraso_backend/apps/story_map/views.py
- terraso_backend/tests/story_map/test_views.py
make media in story map chapters nullable, remove multiple file validation since more than one file can be uploaded per storymap, add more extensive unit tests
> fix: make media in chapters nullable and remove multiple file check

- Makefile
In `Makefile`, pass `—resolver=backtracking` to pip-compile silence warnings about the deprecated resolver.
> fix: pass —resolver=backtracking to pip-compile

- requirements.txt
- terraso_backend/apps/graphql/schema/commons.py
We were manually reproducing a bunch of logic from our dependency graphene in `TerrasoConnection` in order to make the GraphQL schema types more accurate, but they have now merged our upstream PR that adds an option to do this change using their code. This PR updates the dependency and removes the reproduced logic.
context: https://github.com/graphql-python/graphene/pull/1504
> feat: remove graphene code that was merged upstream

- terraso_backend/apps/graphql/schema/sites.py
- terraso_backend/tests/graphql/mutations/test_sites.py
When adding the privacy field to sites I needed to do that weird thing you have to do with enums. I did not do the weird thing. I only added tests for the query not the mutations so I didn't notice I'd forgotten to do the weird thing.
> fix: site privacy mutations

- terraso_backend/apps/core/models/landscapes.py
Check if landscape's default group is not None before attempting to delete it.
Fixes #721.
> fix: check if default group is not None before deleting

- Makefile
Remove deprecated `—rc` argument passed to `isort`.
>https://pycqa.github.io/isort/docs/upgrade_guides/5.0.0.html
>
>--recursive or -rc
>Prior to version 5.0.0, isort wouldn't automatically traverse directories. The --recursive option was necessary to tell it to do so. In 5.0.0 directories are automatically traversed for all Python files, and as such this option is no longer necessary and should simply be removed.
> fix: remove deprecated --rc argument for isort

- requirements.txt
- terraso_backend/tests/graphql/test_projects_query.py
This reverts commit 4451a802a795626cf91c232fe0dfa93f761c2df5.
Seems to be the cause of https://github.com/techmatters/terraso-mobile-client/issues/291.
Will need to create bug report with project if that it the case.
Fixes #....
> fix: Revert "build(deps): bump graphene-django from 3.1.3 to 3.1.5 (#733)"

- terraso_backend/apps/graphql/schema/projects.py
- terraso_backend/apps/project_management/models/projects.py
Added a timestamp to a project group name. This makes it so that there is practically no chance of project creation failing because the associated group has the same name as the project.
Fixes #....
> fix: Save unique project group names

- terraso_backend/apps/graphql/schema/memberships.py
- terraso_backend/apps/graphql/schema/projects.py
- terraso_backend/apps/graphql/schema/sites.py
- terraso_backend/apps/graphql/signals.py
- terraso_backend/apps/project_management/apps.py
- terraso_backend/apps/project_management/signals.py
- terraso_backend/tests/graphql/mutations/test_projects.py
- terraso_backend/tests/graphql/mutations/test_sites.py
Added audit logs for:
- Project membership added
- Project membership updated
- Project updated
Fixed params for:
- Site update audit log project ID
Fixes #763 
Fixes #701 
Fixes #702 
Fixes #551 
Fixes #553
> feat: Project logs audit logs

- terraso_backend/apps/auth/middleware.py
- terraso_backend/apps/auth/services.py
- terraso_backend/tests/auth/test_access_tokens.py
- Fixed test user token validation
- Added access token tests
> fix: Added tests for access tokens, validate if test token

- terraso_backend/apps/collaboration/models/memberships.py
- terraso_backend/apps/graphql/schema/schema.graphql
- terraso_backend/apps/project_management/graphql/projects.py
- terraso_backend/apps/project_management/models/projects.py
This matches what the frontend expects, especially wrt to roles etc. I had to redefine the utility method `get_member` to explicity use the ProjectMembership object manager. There might be a more elegant way of doing this with extending object managers, but I think that this will do the trick for now.
Part of https://github.com/techmatters/terraso-mobile-client/issues/37
> fix: Use ProjectMembershipNodes in Project mutation return types

- terraso_backend/apps/project_management/graphql/projects.py
- terraso_backend/tests/graphql/mutations/test_projects.py
For adding a user to a project, the plan is to use the project info in the redux store in the app to determine if a user belongs to a project. This would create a corner case where a user might be added to the same project twice. (Actually, I think that would exist regardless). This commit just treats that case a succesful operation and does nothing, which seems like the simplest solution to me. In the future we might want to return different error statuses if the user was already added.
Related somewhat to https://github.com/techmatters/terraso-mobile-client/issues/37
> feat: Ignore duplicate adding user to project

- terraso_backend/apps/graphql/schema/story_maps.py
- terraso_backend/apps/story_map/permission_rules.py
- terraso_backend/tests/graphql/mutations/test_story_map_mutations.py
- Added permissions validation context for story map approve membership mutation
- Make story map invitation approve mutation require authentication
Fixes https://github.com/techmatters/terraso-web-client/issues/1196
> fix: Added permissions validation context to api error

- terraso_backend/apps/project_management/graphql/projects.py
- terraso_backend/tests/graphql/test_projects_query.py
- terraso_backend/tests/graphql/test_sites_query.py
Only users who are a member of a project should be able to query the GraphQL backend to find the members of projects to which they belong.
Fixes #....
> fix: Limit project query to member of project

- terraso_backend/apps/audit_logs/services.py
Make audit log timestamps timezone-aware when needed
See https://stackoverflow.com/questions/18622007/runtimewarning-datetimefield-received-a-naive-datetime
Fixes #657.
> fix: make audit log timestamps timezone-aware when needed

- terraso_backend/apps/graphql/schema/sites.py
- terraso_backend/apps/project_management/models/projects.py
- terraso_backend/apps/project_management/permission_rules.py
- terraso_backend/tests/conftest.py
- terraso_backend/tests/graphql/mutations/test_sites.py
This change just allows contributors to create sites. I also updated the site creation test to test this.
Fixes #....
> fix: Allow contributors to create sites

- terraso_backend/apps/collaboration/signals.py
- terraso_backend/tests/collaboration/test_signals.py
Case-insensitive email address matching for storymap invites.
Frontend change to prevent accidental capitalizations: https://github.com/techmatters/terraso-web-client/pull/1232
> fix: case-insensitive email address matching for storymap invites

- terraso_backend/apps/collaboration/models/memberships.py
Additional case-insensitive matching for story map invitation email addresses.
> fix: case-insensitive matching for story map invitation email addresses

- terraso_backend/apps/graphql/schema/sites.py
- terraso_backend/tests/conftest.py
- terraso_backend/tests/graphql/mutations/test_sites.py
Previously this mutation allowed changing the Site to a different project, but not from *all* projects. This PR fixes that.
Necessary for https://github.com/techmatters/terraso-mobile-client/issues/431
> fix: Allow removing site from project

- terraso_backend/apps/core/migrations/0046_shared_resource.py
- terraso_backend/apps/shared_data/migrations/0015_dataentry_groups_move_data.py
- terraso_backend/apps/shared_data/migrations/0016_remove_dataentry_groups_and_more.py
There was an issue running the DB migrations for an empty DB because of apps dependencies, I moved the data migration for data entry groups to the correct app.
> fix: Moved data entries group data migration to shared_data app

- terraso_backend/apps/graphql/schema/schema.graphql
- terraso_backend/apps/project_management/graphql/site_notes.py
Needs a Terraso Connection for django-graphene to pick up on the fact that there are no null objects in the connection.
> fix: Set SiteNoteNode to be not null

- terraso_backend/apps/auth/services.py
- terraso_backend/config/settings.py
* Add MS and Apple mobile login support
* Fix token verification logic. Google sends alg, which is optional, and kty. MS only sends kty. kty is required — we should only enforce that.
> fix: add MS and Apple mobile login support

- terraso_backend/apps/project_management/graphql/projects.py
- terraso_backend/tests/graphql/mutations/test_projects.py
The GraphQL type allows this, but we were trying to access the privacy regardless of whether it was null or not.
Fixes #....
> fix: Allow updates with null privacy

- terraso_backend/apps/graphql/schema/commons.py
- terraso_backend/apps/graphql/schema/sites.py
- terraso_backend/apps/project_management/graphql/projects.py
- terraso_backend/tests/graphql/mutations/test_projects.py
- terraso_backend/tests/graphql/mutations/test_sites.py
- Added sites transfer audit log
- Added site delete audit log
- Added project delete audit log
- https://github.com/techmatters/terraso-backend/issues/773
- https://github.com/techmatters/terraso-backend/issues/772
- https://github.com/techmatters/terraso-backend/issues/771
> feat: Site and Project audit logs

- terraso_backend/apps/core/gis/parsers.py
- terraso_backend/tests/core/gis/test_parsers.py
- terraso_backend/tests/graphql/conftest.py
- terraso_backend/tests/shared_data/conftest.py
Add support for GPX map uploads.
Fixes https://github.com/techmatters/terraso-product/issues/471.
Web client: https://github.com/techmatters/terraso-web-client/pull/1330
> feat: Add support for GPX map uploads

- terraso_backend/apps/shared_data/forms.py
Assume https for URLField. Removes deprecation warning.
> fix: assume https for URLField

- terraso_backend/apps/graphql/schema/schema.graphql
- terraso_backend/apps/project_management/graphql/projects.py
- terraso_backend/tests/graphql/mutations/test_projects.py
Ran into a bug on the frontend when I tried creating a new project. This commit makes sure that the project has a soil project settings associated it. It also allows this to be disabled if we're creating a project from somewhere where the project soil settings is not necessary.
Will also need to make a change to client-shared too.
Fixes #....
> fix: Create project soil settings on project creation

- requirements-dev.txt
- requirements.txt
- requirements/deploy.in
Remove `ddtrace`, as it is not used. We are now using Sentry, which is duplicative.
> chore: remove ddtrace

- .env.sample
- terraso_backend/config/settings.py
Description
===
Since the application crashes with an invalid/incomplete Sentry DSN, and it seems somewhat unnecessary for local dev, I made it optional. (Should this perhaps also detect if it's in production and still crash in case of misconfigurations?)
Let me know what you think, and feel free to close the issue if you don't like the idea altogether.
Changes:
- Log a warning and continue when sentry DSN is absent
There are no tests for settings.py. I'd have to mock out awkward things to make a meaningful test for this, but I'm happy to do so if desired.
- `make run` with SENTRY_DSN absent from .env
- `make run` with SENTRY_DSN present in .env
- Deploy the application and ensure sentry traces are still being sent
> chore: Make Sentry config optional

- terraso_backend/apps/collaboration/models/memberships.py
- terraso_backend/tests/graphql/test_groups.py
-  Use user id to filter membership to work with anonymous users
- https://github.com/techmatters/terraso-web-client/issues/1409
> fix: Use user id to filter membership to work with anonymous users

- terraso_backend/apps/core/management/commands/harddelete.py
- terraso_backend/config/settings.py
- terraso_backend/tests/core/commands/test_harddelete.py
Don't delete users when cleaning up old models. Preserves integrity of audit log.
> fix: don't delete users when cleaning up old models

- terraso_backend/apps/auth/services.py
- terraso_backend/apps/auth/views.py
- terraso_backend/tests/auth/test_views.py
- Added parameter inside token to know if the user was created with a service
- https://github.com/techmatters/terraso-web-client/issues/1145
> feat: Set is first login value inside token

- terraso_backend/apps/graphql/schema/sites.py
- terraso_backend/apps/project_management/models/sites.py
- terraso_backend/apps/project_management/permission_rules.py
- terraso_backend/tests/graphql/mutations/test_sites.py
Fix problems with site contributor permissions by granting the "change site" permission to project contributors. Restrict the name, privacy, and project id fields to owner/manager to maintain access restrictions parity with mobile client. Add test cases verifying new access controls.
Fixes [#843](https://github.com/techmatters/terraso-mobile-client/issues/843), [#925](https://github.com/techmatters/terraso-mobile-client/issues/925), [#851](https://github.com/techmatters/terraso-mobile-client/issues/851)
Create a project and a site as one user, then add a second user to the site as a contributor. Verify that the second user can now update soil data, crack data, texture data. Verify that the second user cannot update the name or privacy, but that the first user still can.
> fix: Update permissions for site contributors to match requirements

- terraso_backend/apps/core/admin.py
Add Django UserAdmin. Allows changing passwords in admin ui.
Fixes #191.
> fix: add Django UserAdmin

- terraso_backend/apps/project_management/graphql/projects.py
- terraso_backend/apps/project_management/models/projects.py
- terraso_backend/tests/graphql/mutations/test_projects.py
- terraso_backend/tests/project_management/models/test_projects.py
Add check to reject project user-deletion requests if the user in question is the only manager for the project. The system was accepting incoming user-removal requests for the project's only manager, despite requirements that removing the only manager on a project is not permitted.
Fixes #[496](https://github.com/techmatters/terraso-mobile-client/issues/496)
See automated tests covering these cases.
> fix: prevent the removal of the only manager from projects

- .github/workflows/build.yml
- Dockerfile
- Makefile
- README.md
- docker-compose.ci.yml
- requirements-dev.txt
- requirements.txt
- requirements/base.in
- requirements/dev.in
- terraso_backend/tests/soil_id/test_soil_id.py
- Use Debian Testing PPA for newer GDAL.
- Add soil id algorithm module dependency
- Download  soil id data via GitHub actions
- Run basic `list_soils` test
This fixes #1267.
> feat: soil id algorithm dependency (with Debian 12)

- terraso_backend/apps/graphql/schema/__init__.py
- terraso_backend/apps/graphql/schema/schema.graphql
- terraso_backend/apps/soil_id/graphql/soil_id.py
- terraso_backend/tests/graphql/test_soil_id.py
Defines GraphQL endpoints for the soil id calls, with dummy data for now. Still need to add tests to validate that the endpoints work/return data with the right shape.
Progress on #1265 and #1266
> feat: soil id endpoints

- Makefile
'make run' now checks if it needs to rebuild the docker image
(Issue surfaced from [this](https://tech-matters.slack.com/archives/C02K02L3Q48/p1715967037419279) slack thread, where a dependency was added but the backend couldn't find it because the docker image had not been updated)
N/A
N/A
See description
> fix: 'make run' now checks if it needs to rebuild the docker image

- requirements.txt
- requirements/base.in
- terraso_backend/apps/graphql/schema/schema.graphql
- terraso_backend/apps/soil_id/graphql/soil_id.py
- terraso_backend/tests/graphql/test_soil_id.py
- terraso_backend/tests/soil_id/test_soil_id.py
Depends on https://github.com/techmatters/soil-id-algorithm/pull/95
Resolves #1270
> feat: wire up data-based soil matches query

- terraso_backend/apps/soil_id/graphql/soil_id.py
Switches the soil ID endpoints back to using dummy data until underlying algorithm bugs are resolved.
Current main on mobile client should have functional soil ID screens now.
> fix: switch back to using dummy data for soil ID endpoints

- terraso_backend/apps/graphql/schema/schema.graphql
- terraso_backend/apps/soil_id/graphql/soil_id/endpoints.py
- terraso_backend/apps/soil_id/graphql/soil_id/resolvers.py
- terraso_backend/apps/soil_id/graphql/soil_id/schema.py
- terraso_backend/tests/soil_id/test_graphql_resolvers.py
Refactors the soil ID algorithm endpoints to always return successfully but provide a specific reason if no results are returned. For now we will not be more granular than saying either "data unavailable" or "algorithm failed", since that would require refactoring the actual algorithm to return more useful output.'
Related to https://github.com/techmatters/terraso-product/issues/895
> feat: refactor soil id endpoints to return more specific error messages

- terraso_backend/apps/soil_id/admin.py
Adds these two change list views:
For each project, shows the project name and the depth interval preset.
When you click on a project, shows project soil settings like required inputs and defined depth intervals.
For each site, shows the site name and the depth interval preset.
When you click on a site, shows entered site data, including data entered at each depth interval (`DepthDependentSoilData`) and interval definitions themselves (`SoilDataDepthIntervals`) -- which I find to be a slightly confusing model but that's how it works :)
N/A
Go to django admin panel, view the two new items
> feat: Display depth interval data and settings in django admin panel

- terraso_backend/apps/project_management/models/projects.py
- terraso_backend/apps/soil_id/admin.py
- terraso_backend/apps/soil_id/models/project_soil_settings.py
- terraso_backend/apps/soil_id/models/soil_data.py
In Django admin panel:
- Add custom plurals when plurals were incorrect
- Add project and site owner to "Soil data"
Now looks like:
N/A
Look at django admin panel
> Fix: Modify admin panel tables and names

- terraso_backend/apps/graphql/schema/schema.graphql
- terraso_backend/apps/graphql/schema/visualization_config.py
- terraso_backend/tests/graphql/conftest.py
- terraso_backend/tests/graphql/test_visualization_config.py
Expose map processing status
- https://github.com/techmatters/terraso-web-client/issues/1941
> feat: Expose map processing status

- terraso_backend/apps/auth/services.py
- terraso_backend/apps/storage/tasks.py
- terraso_backend/tests/auth/test_services.py
Created async task to run profile image update
- https://github.com/techmatters/terraso-backend/issues/1371
> refactor: Async execution of update profile image

- terraso_backend/apps/soil_id/admin.py
- terraso_backend/apps/soil_id/models/soil_id_cache.py
add Soil ID Cache to Django admin.
> feat: add Soil ID Cache to Django admin

- docker-compose.base.yml
- docker-compose.ci.yml
- docker-compose.dev.yml
remove version from docker-compose file
Addresses:
WARN[0000] /Users/paul/.dev/backend/docker-compose.dev.yml: the attribute `version` is obsolete, it will be ignored, please remove it to avoid potential confusion
> fix: remove version from docker-compose file

- Dockerfile
use ENV key=value format in Dockerfile
Fixes
```
2 warnings found (use docker --debug to expand):                                             
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 5)
- LegacyKeyValueFormat: "ENV key=value" should be used instead of legacy "ENV key value" format (line 7)
```
> build: use ENV key=value format in Dockerfile

- terraso_backend/apps/project_management/migrations/0003_remove_site_project_management_site_unique_active_slug_and_more.py
- terraso_backend/apps/soil_id/migrations/0003_alter_depthdependentsoildata_options_and_more.py
- terraso_backend/apps/soil_id/migrations/0005_projectdepthinterval_projectsoilsettings_and_more.py
- terraso_backend/apps/soil_id/models/depth_interval.py
- terraso_backend/config/settings.py
* replace CheckConstraint.check with CheckConstraint.condition 
*  add FORMS_URLFIELD_ASSUME_HTTPS=True
Fixes two warnings:
```
RemovedInDjango60Warning: CheckConstraint.check is deprecated in favor of `.condition`.
```
```
RemovedInDjango60Warning: The default scheme will be changed from 'http' to 'https' in Django 6.0. Pass the forms.URLField.assume_scheme argument to silence this warning, or set the FORMS_URLFIELD_ASSUME_HTTPS transitional setting to True to opt into using 'https' as the new default scheme.
```
> fix: replace CheckConstraint.check with CheckConstraint.condition and add FORMS_URLFIELD_ASSUME_HTTPS

- requirements-dev.txt
- requirements.txt
- requirements/base.in
- terraso_backend/apps/core/gis/parsers.py
- terraso_backend/apps/soil_id/graphql/soil_id/resolvers.py
- terraso_backend/tests/graphql/test_shared_data.py
- terraso_backend/tests/soil_id/test_graphql_resolvers.py
- Update to current soil ID
- Update associated dependencies
- Restore edit_url fix
- Use fiona driver for geopandas
> fix: update soil id

- terraso_backend/apps/graphql/schema/schema.graphql
- terraso_backend/apps/graphql/schema/shared_resources_mixin.py
- terraso_backend/apps/graphql/schema/visualization_config.py
- https://github.com/techmatters/terraso-web-client/issues/2289
> refactor: Optimize maps queries

- terraso_backend/apps/soil_id/models/soil_data_history.py
- terraso_backend/tests/graphql/mutations/test_soil_data.py
Fixes the bug with enum fields in the soil data push mutation, and takes some steps towards more robust testing.
Related to the testing part of #1487.
> fix: enum fields in soil data push

- .github/workflows/build.yml
move Data/ path prefix from hashFiles() call. Hopefully will result in cache named `Linux-data-xyz` instead of `Linux-data-`.
> fix: remove Data/ path prefix from hashFiles() call

- docker-compose.base.yml
To upgrade your local development environment
With Postgres 14: ensure your backend Docker container is running (`make run`).
Back up your database:
```
CONTAINER_ID=`docker ps | grep postgis | cut -c 1-12`
docker exec -it  ${CONTAINER_ID} pg_dumpall -U postgres > terraso.sql
```
Delete the data directory:
```
docker compose -f docker-compose.dev.yml down
docker volume rm backend_postgresql_data
```
With Postgres 16: ensure your backend Docker container is running (`make run`).
Restore the data:
```
CONTAINER_ID=`docker ps | grep postgis | cut -c 1-12`
cat terraso.sql| docker exec -i ${CONTAINER_ID} psql -U postgres
```
> build: update posgres to 16

- requirements-dev.txt
- requirements.txt
> build: update boto/botocore

- requirements.txt
> build: bump django-ses to 4.3.1

- terraso_backend/apps/soil_id/graphql/soil_id/resolvers.py
- terraso_backend/tests/soil_id/test_graphql_resolvers.py
Fix the soil ID request resolver to handle some edge cases in the algorithm's return values for LCC.
Related to https://github.com/techmatters/soil-id-algorithm/issues/119
> fix: lcc resolver

- terraso_backend/apps/graphql/schema/story_maps.py
- terraso_backend/tests/graphql/conftest.py
- terraso_backend/tests/graphql/test_story_map.py
- Added signed urls for published story map configuration
- https://github.com/techmatters/terraso-web-client/issues/2631
> fix: Sign media urls for published configuration

- terraso_backend/apps/soil_id/graphql/soil_data/push_mutation.py
- terraso_backend/tests/graphql/mutations/test_soil_data.py
**Previously**: Editing a depth interval could cause a conflict if the new depth interval overlapped the old one:
```{"data":{"pushSoilData":{"results":[{"siteId":"6652e310-0938-48c6-99f8-b2895183004e","result":{"__typename":"SoilDataPushEntryFailure","reason":"INVALID_DATA"}}],"errors":null}}}```
This is because it would try to add the new interval to the site, validate the site's intervals (where it could fail), and then delete the old interval. This would cause the old interval to stay around, though a new interval would also appear, and the project conflict dialog would show.
**Now**: Delete the old interval before trying to add the new interval to the site. Honestly I didn't investigate why the project conflict dialog would show, but it no longer does. Also add a test.
Addresses …
> Fix: Editing depth interval should remove old interval earlier

- Dockerfile
- requirements.txt
- requirements/base.in
use updated soil-id with GDAL 3.10.3.
> build: use updated soil-id with GDAL 3.10.3

- terraso_backend/apps/soil_id/graphql/soil_id/resolvers.py
- terraso_backend/tests/soil_id/test_graphql_resolvers.py
`parse_rock_fragment_volume` would always return “>60%“, even when I selected another value range. I believe this was because according to Python's `type(obj)`:
- The input type is `<enum 'SoilIdDepthDependentSoilDataRockFragmentVolumeChoices'>`
- The type we’re comparing to is `<enum 'RockFragmentVolume'>`
I'm wondering how to refer to the `SoilIdDepthDependentSoilDataRockFragmentVolumeChoices` to replace the type hint, and to pass in the test? It looks like only schema.graphql defines the type, and it doesn’t seem like we import things from that file?
One of the things for [#1691](https://github.com/techmatters/terraso-backend/issues/1691)
> fix: parse_rock_fragment_volume no longer always returns >60%

- terraso_backend/apps/soil_id/graphql/soil_id/resolvers.py
- terraso_backend/tests/soil_id/test_graphql_resolvers.py
Previously it was always returning False.
Also add a test.
Weird stuff: 
- Changing the surface cracks still appears to have no affect on the match scores
- We offer users 3 cracking options but the soil-id-algorithm just expects a boolean
Part of https://github.com/techmatters/terraso-product/issues/1279
> Fix: parse_surface_cracks should return true for Deep Vertical Cracks

- terraso_backend/apps/auth/views.py
- terraso_backend/config/settings.py
- terraso_backend/tests/auth/test_views.py
Updates the backend to support a new login method to use for preview branches. Clients logging in from a different apex domain than the backend is on will now get their tokens passed via query parameters instead of via cookies (which is not possible when on a different apex domain). This is not enabled in production because it's less secure.
Tests TBD.
Related to #1709
Old web clients should still work. New web clients should be able to log in from other domains (still subject to CORS restrictions).
> feat: allow clients to login from different domains

- docker-compose.base.yml
- scripts/rebuild.sh
I started getting an error ‘no matching manifest for linux/arm64/v8 in the manifest list entries’ when running ‘make run’. 
My understanding is that the postgis/postgis image we use only specifies that it can run on linux/amd64, but my mac uses Apple Silicon’s ARM architecture. Docker has a setting to use amd64 emulation on Apple Silicon, but it seems like this change was needed to get Docker to actually build the container from the image.
I’m not sure why it was working before, though…? It started happening after a git pull and after deleting a bunch of docker objects in Docker Desktop to free up disk space.
Made the change per this: https://stackoverflow.com/questions/65456814/docker-apple-silicon-m1-preview-mysql-no-matching-manifest-for-linux-arm64-v8 
And confirmed that the listed …
> fix: Docker should build the db container on arm64 architecture
