techmatters/terraso-backend

terraso_backend/config/settings.py

This change handles the Apple private key format coming from environment
variable.

fix: handle Apple private key format

---

README.md

Update readme with current name of run script.

docs: update readme with current name of run script

---

sampledata.json

This change updates sample data according to the latest information on
AirTable.
- #68

chore: update sample data

---

terraso_backend/apps/graphql/schema/memberships.py

This change adds more filter options to the Membership schema on
GraphQL.
It fixes:
- #71

feat: add Membership filters on GraphQL

---

terraso_backend/apps/graphql/schema/users.py
terraso_backend/tests/graphql/test_core_request.py

- Added profile image to User Graph QL Schema
Fixes #22

fix: Added profile image to graph QL schema

---

terraso_backend/apps/core/migrations/0005_auto_20220113_1747.py

This change fixes a migration leaf / name conflict.

fix: migration conflict

---

sampledata.json

Removes relationship from Group that doesn't exist anymore on sample
data.

fix: sample data

---

sampledata.json

Fix spelling of peninsula is sample data.

fix: fix spelling of peninsula

---

terraso_backend/apps/auth/urls.py
terraso_backend/apps/auth/views.py
terraso_backend/tests/auth/test_views.py

Remove unused `/auth/user` endpoint.
Fixes #86.

fix: remove /auth/user endpoint

---

terraso_backend/apps/graphql/schema/users.py
terraso_backend/tests/graphql/mutations/test_user_mutations.py

This change adds the permissions check to change and delete User
mutations. Only the user itself can perform these operations.
- #75

feat: add permissions to User change and delete mutations

---

terraso_backend/apps/graphql/schema/memberships.py
terraso_backend/tests/graphql/mutations/test_membership_mutations.py

This change refactor add and change mutations for Membership. Before
both mutations were inheriting the same base one. However, after
including the validations, the process of each mutation became more
distinct.
Separating them makes possible to increase the efficiency, for example.
On change mutation, the process was querying for the Membership on
database twice. Now it fetches the data only once. Among other
improvements like checking for User and Group models existence when
creating a new Membership.

refactor: Membership Add and Change mutations

---

README.md

Updates the README with information on how to load GeoJSON data and how to flush the database.

docs: add load geodata and flush db commands to README

---

sampledata.json

This change updates the uMngeni Landscape description on sample data,
based on text on AirTable.

chore: update uMngeni Landscape description on sample data

---

terraso_backend/apps/core/models/landscapes.py
terraso_backend/tests/core/models/test_landscapes.py

- Add landscape deafult group on landscape creation
- Set manager when landscape is created
Fixes #140

feat: Landscape default group and manager

---

terraso_backend/apps/graphql/schema/landscapes.py

- Added areaPolygon to landscape create payload

feat: Save area on landscape creation

---

terraso_backend/apps/auth/services.py

This change updates the process of setting user's profile image to
attempt to download (and update) user's profile image on every login.
This is necessary to mitigate the following issue. So, user's profile
image can be updated without having to remove the account from 
Terraso:
- https://github.com/techmatters/terraso-web-client/issues/363

feat: attempt to update profile image on every login

---

requirements-dev.txt
requirements.txt
requirements/base.in

fix: Update python dependencies

---

terraso_backend/apps/shared_data/forms.py
terraso_backend/tests/shared_data/test_views.py

- Added custom CSV validation
Fixes https://github.com/techmatters/terraso-backend/issues/171

Fix: CSV validation

---

terraso_backend/apps/graphql/schema/landscapes.py
terraso_backend/tests/graphql/mutations/test_landscape_mutations.py

Just a small change that lets us change the profile photo values from the frontend.

feat: Add changes to delete landscape profile photo

---

terraso_backend/apps/core/admin.py
terraso_backend/apps/core/migrations/0027_spanish_taxonomy_terms.py

- Added spanish taxonomy terms

chore: Spanish taxonomy terms

---

requirements.txt
requirements/base.in
terraso_backend/apps/graphql/schema/commons.py
terraso_backend/apps/graphql/schema/group_associations.py
terraso_backend/apps/graphql/schema/landscape_groups.py
terraso_backend/apps/graphql/schema/memberships.py
terraso_backend/apps/graphql/schema/users.py
terraso_backend/apps/graphql/spectaql.yml
terraso_backend/config/settings.py
terraso_backend/tests/graphql/mutations/test_group_associations_mutations.py
terraso_backend/tests/graphql/mutations/test_group_mutations.py
terraso_backend/tests/graphql/mutations/test_landscape_groups_mutations.py
terraso_backend/tests/graphql/mutations/test_landscape_mutations.py
terraso_backend/tests/graphql/mutations/test_membership_mutations.py
terraso_backend/tests/graphql/mutations/test_shared_data_mutations.py
terraso_backend/tests/graphql/mutations/test_user_mutations.py
terraso_backend/tests/graphql/mutations/test_visualization_config_mutations.py
terraso_backend/tests/graphql/test_taxonomy_terms.py

- graphene upgrade
- Changed how mutation errors ar handled
Fixes #....

chore: graphene upgrade

---

terraso_backend/apps/graphql/views.py
terraso_backend/tests/graphql/test_auth_request.py

- Enable local GraphQL authentication to avoid graph ql request without valid user

fix: Enable local GraphQL authentication

---

.github/dependabot.yml

chore: enable dependabot updates

---

.github/workflows/build.yml
.github/workflows/check-commits.yml

- Uses Node 16
- Avoids deprecation warnings

chore: update GitHub actions versions

---

.github/workflows/build.yml
Dockerfile

chore: update python to 3.11.1

---

terraso_backend/custom_templates/oauth2_provider/authorize.html
terraso_backend/tests/auth/conftest.py
terraso_backend/tests/auth/test_templates.py

Adds a test to make sure the SSO authorization template is being rendered successfully. Also adjusts the wording to match the specifications.

feat: Change auth template to match spec

---

terraso_backend/apps/graphql/schema/story_maps.py
terraso_backend/apps/story_map/migrations/0004_remove_storymap_story_map_storymap_unique_active_slug_and_more.py
terraso_backend/apps/story_map/models/story_maps.py
terraso_backend/apps/story_map/views.py

Added story map url identifier, this removes the need to validate the uniqueness for the title
Fixes #....

feat: Story map url identifier

---

.env.sample

Update `.env.sample` to sync with changes introduced in #343.
* remove Google/Apple/MS API URLs
* add API_ENDPOINT

fix: add API_ENDPOINT to .env.sample

---

.github/workflows/build.yml
Dockerfile

chore: update Python to 3.11.2

---

.github/workflows/build.yml
Makefile
README.md
docker-compose.base.yml
docker-compose.ci.yml
docker-compose.dev.yml
scripts/run.sh

Refactor docker-compose files by environmental. Allows CI to not mount /app volume.

feat: docker-compose inheritance and makefile updates

---

terraso_backend/apps/story_map/migrations/0004_remove_storymap_story_map_storymap_unique_active_slug_and_more.py
terraso_backend/apps/story_map/views.py

Simplify story map ID generation by using `secrets`.

fix: simplify story map ID generation

---

terraso_backend/apps/auth/middleware.py
terraso_backend/apps/auth/urls.py
terraso_backend/apps/graphql/schema/__init__.py
terraso_backend/apps/graphql/schema/commons.py
terraso_backend/apps/graphql/schema/data_entries.py
terraso_backend/apps/graphql/schema/story_maps.py
terraso_backend/apps/graphql/urls.py
terraso_backend/apps/graphql/views.py
terraso_backend/config/settings.py
terraso_backend/tests/graphql/conftest.py
terraso_backend/tests/graphql/mutations/test_group_mutations.py
terraso_backend/tests/graphql/test_auth_request.py
terraso_backend/tests/graphql/test_shared_data.py
terraso_backend/tests/graphql/test_story_map.py

- Added optional authentication decorator
- Added settings list for public base paths
- Made GraphQL endpoints optionally authenticated
- Improved JWT validation to raise exceptions
- Fixed Graph QL filters using user data to handle anonymous users
Fixes https://github.com/techmatters/terraso-web-client/issues/775

feat: Public view support

---

Makefile

allow passing PATTERN to make test.
i.,e,
```
PATTERN="test_users_unsubscribe_update" make test
```

fix: allow passing PATTERN to make test

---

terraso_backend/apps/core/models/groups.py
terraso_backend/apps/graphql/schema/data_entries.py
terraso_backend/apps/graphql/schema/visualization_config.py
terraso_backend/apps/shared_data/models/data_entries.py
terraso_backend/apps/shared_data/models/visualization_config.py
terraso_backend/apps/shared_data/permission_rules.py

Add permission checks for creating maps and shared files
Fixes https://github.com/techmatters/terraso-web-client/issues/811
Web client https://github.com/techmatters/terraso-web-client/pull/859

fix: add permission checks for creating maps and shared files

---

.github/workflows/build.yml
Dockerfile

chore: update python to 3.11.3

---

terraso_backend/apps/core/models/landscapes.py
terraso_backend/apps/graphql/schema/schema.graphql
terraso_backend/apps/graphql/templates/docs.html

This removes unused i18n code from the landscape model that was tripping up the graphql schema lint step in CI.  
Unblocks #511 
Everything should work the same, CI should run successfully.

fix: graphql schema output was not consistent

---

terraso_backend/tests/graphql/mutations/test_shared_data_mutations.py

This just adds a unit test as a follow-up to #546 since i didn't realize how to write graphql mutation tests before then.
Tests pass.

test: unit test for adding shared link

---

requirements-dev.txt
requirements.txt

chore: update dependencies

---

.github/workflows/build.yml
Dockerfile

chore: update python to 3.11.4

---

terraso_backend/apps/graphql/schema/__init__.py
terraso_backend/apps/graphql/schema/commons.py
terraso_backend/apps/graphql/schema/projects.py
terraso_backend/apps/graphql/schema/schema.graphql
terraso_backend/apps/graphql/schema/sites.py
terraso_backend/apps/graphql/templates/docs.html
terraso_backend/apps/project_management/models/sites.py
terraso_backend/apps/project_management/permission_rules.py
terraso_backend/tests/graphql/mutations/test_sites.py
terraso_backend/tests/graphql/test_projects_query.py
terraso_backend/tests/graphql/test_sites_query.py

This PR makes small changes needed for https://github.com/techmatters/terraso-client-shared/issues/18 and https://github.com/techmatters/terraso-client-shared/issues/17. It is in draft while I am working on the frontend code for those issues.

feat: improve project & site graphql schema

---

terraso_backend/apps/graphql/schema/projects.py
terraso_backend/apps/graphql/schema/schema.graphql
terraso_backend/apps/graphql/templates/docs.html
terraso_backend/apps/project_management/models/projects.py
terraso_backend/tests/graphql/mutations/test_projects.py

Forgot to update the GraphQL Node fields as well

fix: Add project description to project GraphQL node

---

terraso_backend/apps/soil_id/migrations/0001_initial.py

update 0001 soil_id migration dependency to reference 0013_remove_site_created_by_project_description

fix: update soil id migration dependency array

---

.env.sample
terraso_backend/config/settings.py

Adds OAuth login functionality to the backend for the ios build
Fixes #697

feat: add oauth redirects to ios 

---

terraso_backend/apps/shared_data/views.py
terraso_backend/apps/story_map/views.py
terraso_backend/config/settings.py
terraso_backend/tests/story_map/test_views.py

Restrict file uploads to allowed extensions list.
Fixes #197 and extends from #198

feat: add backend checks for shared data uploads

---

terraso_backend/apps/graphql/schema/projects.py
terraso_backend/apps/graphql/schema/schema.graphql

Add archived field in project node

feat: add archived field in project node

---

terraso_backend/apps/core/landscapes_views.py
terraso_backend/apps/core/urls.py
terraso_backend/tests/core/test_landscapes_views.py

Added view to get landscape data in json format
Fixes https://github.com/techmatters/terraso-web-client/issues/813

feat: Added view to get landscape data in json format

---

Makefile

Adds the django `showmigrations` command to the project's Makefile.

feat: add showmigrations command to Makefile

---

terraso_backend/apps/auth/middleware.py
terraso_backend/apps/auth/services.py
terraso_backend/apps/auth/views.py
terraso_backend/apps/graphql/schema/users.py
terraso_backend/tests/auth/test_token_exchange.py
terraso_backend/tests/core/test_landscapes_views.py

- Added intent to tokens payload and added intent validation

fix: Added intent to tokens payload and added intent validation

---

terraso_backend/apps/core/landscapes_views.py
terraso_backend/tests/core/test_landscapes_views.py

- Added new field for associted groups and organizations for landscape export
Fixes https://github.com/techmatters/terraso-web-client/issues/1176

fix: Added new field for groups and organizations

---

terraso_backend/apps/project_management/models/projects.py
terraso_backend/tests/graphql/mutations/test_projects.py

fix: fix create project

---

.github/workflows/build.yml
Dockerfile

chore: update python to 3.12.0

---

README.md
terraso_backend/apps/auth/providers.py

Support both authentication methods (secret or certificates) for MS SSO.
Update README with MS SSO environment variables.

fix: support both authentication methods for MS SSO

---

terraso_backend/apps/project_management/admin.py

Add site and project names to sites/projects admin list view.

fix: add names to sites/projects admin list view

---

terraso_backend/apps/shared_data/models/data_entries.py

Remove groups field from shareddata docs. Field was previously removed.

docs: remove groups field from shareddata docs

---

requirements-dev.txt
requirements.txt

Update Python dependencies (boto3/botocore).

chore: update boto3/botocore

---

terraso_backend/apps/project_management/graphql/projects.py

Fix: Allow project updates without name

---

terraso_backend/apps/graphql/schema/data_entries.py
terraso_backend/tests/graphql/mutations/test_shared_data_mutations.py

Data entries are showing even when deleted when fetched from the shared resource target.
Because of the SafeDelete functionality compatibility with a Generic relationship and to remove the relationships with Group and Landscapes when a data entry is deleted the shared resources have to be deleted explicitely.

fix: Delete shared resources when deleting data entry

---

terraso_backend/apps/core/models/landscapes.py

Add plural name for landscape development strategies.

fix: add plural name for landscape development strategies

---

README.md
scripts/commit-msg.sample

The commit bodies have a little more context. Should I paste that here as well?
- Mention minimum Docker version in README
- Use more universally available path for system Python in pre-commit hook
- Make a commit on macOS

Chore: Minor local dev improvements

---

.github/workflows/build.yml
Dockerfile

Update python from 3.12 to 3.12.1.

chore: bump python to 3.12.1

---

.github/workflows/build.yml
Dockerfile

fix: bump python to 3.12.2

---

terraso_backend/apps/core/models/landscapes.py

docs: fix spelling of stakeholders

---

.github/workflows/build.yml
Dockerfile

fix: bump python to 3.12.3

---

.env.sample
requirements.txt
requirements/base.in
terraso_backend/apps/core/hubspot.py
terraso_backend/apps/core/management/commands/ticket.py
terraso_backend/config/settings.py

Create account deletion form via hubspot API.
First part of #1112.

feat: Create account deletion form via hubspot API

---

terraso_backend/apps/graphql/schema/schema.graphql
terraso_backend/apps/soil_id/graphql/soil_id.py
terraso_backend/tests/graphql/test_soil_id.py

returns actual soil id algorithm data from our graphql endpoint!
this depends on both #1273 and #1290 so it's based on a merge of the two branches, this will need to be cleaned up before merging this
Related to #1269

feat: wire up soil id algorithm

---

docs/apple_certificates.md

Explain apple certificates, identifiers and profiles.

docs: explain apple certificates, identifiers and profiles

---

terraso_backend/apps/soil_id/graphql/soil_id.py
terraso_backend/tests/graphql/test_soil_id.py

Fixes some bugs in parsing the output of the soil ID algorithm. Also updates the tests which were not catching the bugs

fix: soil id algorithm result parsing

---

requirements.txt
requirements/base.in
terraso_backend/tests/auth/test_access_tokens.py
terraso_backend/tests/graphql/conftest.py

Bump graphene-django from 3.1.5 to 3.2.0.

build: bump graphene-django from 3.1.5 to 3.2.0

---

requirements.txt
requirements/base.in

update grahene-django to 3.2.2.

build: update grahene-django to 3.2.2

---

terraso_backend/apps/core/models/users.py
terraso_backend/apps/graphql/schema/users.py

- add account deletion request preference
- when created and set to true
Addresses https://github.com/techmatters/terraso-backend/issues/1112

feat: add account deletion request preference

---

requirements-dev.txt
requirements.txt

build: update boto3 and openpyxl

---

terraso_backend/apps/soil_id/graphql/soil_id/resolvers.py

Re-enables the soil ID algorithm. Done as an individual PR so it's easy to revert. Depends on #1329

feat: re-enable soil id algorithm

---

terraso_backend/apps/auth/services.py

Ensure no default value is set for USER_PREFS_KEY_ACCOUNT_DELETION upon account createion.

fix: ensure no default value for USER_PREFS_KEY_ACCOUNT_DELETION

---

requirements-dev.txt
requirements.txt

Update boto3, django-cors-headers

build: update dependencies

---

terraso_backend/apps/soil_id/graphql/soil_id/resolvers.py

Re-enables the soil ID algorithm. Stacked on #1329, and should be merged to main after #1329 is merged so that it's easy to revert.

feat: enable soil ID algorithm

---

requirements.txt
requirements/base.in

Update to the current version of soil-id.

build: update soil ID commit

---

terraso_backend/apps/collaboration/admin.py
terraso_backend/apps/soil_id/admin.py

Adds a few fields and search bars to some of the django admin pages
Once it is merged to staging, look at https://api.staging.terraso.net/admin/

feat: Add to django admin pages

---

requirements.txt
requirements/base.in

bump fiona to 1.10b3. avoids GCC 14 problem.

build: bump fiona to 1.10b3

---

terraso_backend/apps/graphql/schema/landscapes.py
terraso_backend/tests/graphql/mutations/test_landscape_membership_mutations.py
terraso_backend/tests/graphql/test_landscape.py

- Added filter set to check for soft deleted memberships
- https://github.com/techmatters/terraso-web-client/issues/1629

fix: Landscape membership soft delete

---

requirements-dev.txt
requirements.txt

build: update boto and botocore

---

.github/workflows/build.yml
Dockerfile

build: bump Python to 3.12.5

---

terraso_backend/apps/soil_id/graphql/soil_id/resolvers.py
terraso_backend/tests/soil_id/test_graphql_resolvers.py

update esd_url to edit_url for compatibility with new soil id endpoint.

fix: update esd_url to edit_url

---

requirements.txt
requirements/base.in

build: set fiona to release version (1.10).

build: set fiona to release version (1.10)

---

requirements-dev.txt
requirements.txt

update boto, botocore, pytest.

build: update boto, botocore, pytest

---

terraso_backend/apps/project_management/models/sites.py

change check= to condition= for Django 6 compatibility.

fix: change check= to condition= for Django 6 compatibility

---

requirements.txt

bump django-oauth-toolkit to 3.0.1.

build: bump django-oauth-toolkit to 3.0.1

---

.github/workflows/build.yml
Dockerfile

build: update Python to 3.12.6

---

terraso_backend/apps/core/management/commands/delete_user.py
terraso_backend/apps/project_management/models/sites.py

Add delete_user command delete a user and its data.
Add string representation for groups.

feat: Add delete_user command delete a user and its data

---

.github/workflows/build.yml
Dockerfile

build: update python to 3.12.7

---

requirements-dev.txt
requirements.txt

update boto. botocore, django-dirty.

build: update boto. botocore, django-dirty

---

requirements.txt
requirements/base.in

update soil id module
- use new endpoint
- get ESD fix

build: update soil id module

---

requirements.txt
requirements/base.in
terraso_backend/apps/core/management/commands/loadbackup.py

replace psycopg2 with psycopg.

fix: replace psycopg2 with psycopg

---

requirements-dev.txt

build: update ipython to 8.30.0

---

requirements-dev.txt

build: update jsonpath commit hash

---

requirements.txt

build: update pyjwt to 2.10.1

---

requirements.txt

update django-structlog  to 9.0.0.

build: update django-structlog  to 9.0.0

---

requirements.txt

build: update imageio to 2.36.1

---

requirements.txt

build: update django-ses to 4.3.0

---

requirements.txt
requirements/base.in

build: update soil-id commit hash

---

requirements.txt
requirements/base.in

update soil-id algorithm commit hash.

build: update soil-id algorithm

---

requirements.txt

build: bump django to 5.1.4

---

requirements-dev.txt
requirements.txt

build: update boto/botocore

---

requirements.txt

build: bump sqlparse to 0.5.3

---

requirements-dev.txt
requirements.txt

build: bump boto3 to 1.35.82

---

.github/workflows/build.yml
Dockerfile

build: update python to 3.13.1

---

requirements.txt
requirements/base.in

update soil-id-algorithm commit hash.

build: update soil-id-algorithm commit hash

---

terraso_backend/apps/core/admin.py

Display id as a readonly field

feat: Add user ID to django admin panel

---

terraso_backend/apps/graphql/schema/schema.graphql
terraso_backend/apps/soil_id/graphql/soil_id/queries.py

Document location based soil matches bug.
Related to https://github.com/techmatters/soil-id-algorithm/issues/126

docs: document location based soil matches bug

---

.github/workflows/build.yml
Dockerfile

build: bump python to 3.13.2

---

Makefile
pyproject.toml
requirements-dev.txt
requirements/dev.in
setup.cfg
terraso_backend/apps/core/gis/utils.py
terraso_backend/apps/core/management/commands/ticket.py
terraso_backend/apps/core/models/shared_resources.py
terraso_backend/apps/graphql/schema/story_maps.py
terraso_backend/apps/graphql/schema/story_maps_memberships.py
terraso_backend/apps/story_map/admin.py
terraso_backend/apps/story_map/models/__init__.py
terraso_backend/apps/story_map/models/story_maps.py
terraso_backend/apps/story_map/permission_rules.py
terraso_backend/apps/story_map/services.py
terraso_backend/apps/story_map/urls.py
terraso_backend/apps/story_map/views.py
terraso_backend/tests/core/commands/test_harddelete.py
terraso_backend/tests/core/test_landscapes_views.py
terraso_backend/tests/graphql/mutations/test_site_notes.py
terraso_backend/tests/graphql/test_sites_query.py
terraso_backend/tests/graphql/test_sites_soil_data_query.py

use ruff instead of flake8, black and isort.

fix: use ruff instead of flake8, black and isort

---

terraso_backend/apps/collaboration/graphql/memberships.py
terraso_backend/apps/graphql/schema/story_maps.py
terraso_backend/tests/graphql/test_story_map.py

- Added fix to show memberhips for stroy map owners
- https://github.com/techmatters/terraso-web-client/issues/1632

fix: Show memberships for story map owner

---

.pre-commit-config.yaml
terraso_backend/apps/graphql/schema/commons.py
terraso_backend/tests/graphql/mutations/test_group_mutations.py

Identify explicit unique errors
- https://github.com/techmatters/terraso-backend/issues/637

fix: Improve how integrity errors are handled
